server {
    listen 80;
    server_name _;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
        try_files $uri =404;
    }

    location /health {
        access_log off;
        add_header Content-Type text/plain;
        return 200 "OK\n";
    }

    location / {
        add_header Content-Type text/plain;
        return 200 "nginx is ready for certbot\n";
    }
}
